name: Deploy to Amazon ECS

on:
  workflow_call:
    inputs:
      aws-region:
        description: "AWS region (e.g. us-west-1)"
        type: 
        required: true
      ecr-repository:
        description: "Amazon ECR repository name"
        type: string
        required: true
      ecs-service:
        description: "Amazon ECS service name" 
        type: string
        required: true
      ecs-cluster:
        description: "Amazon ECS cluster name"
        type: string
        required: true
      ecs-task-definition:
        description: "Path to Amazon ECS task definition file"
        type: string
        required: true
      container-name:
        description: "Name of the container in task definition"
        type: string
        required: true

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ github.sha }} .
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ github.sha }}
        echo "image=${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ github.sha }}" >> $GITHUB_OUTPUT
    
    - name: Get ECS task definition
      id: task-definition
      run: |
        echo "task-definition=$(aws ecs describe-task-definition \
        --task-definition ${{ inputs.task_definition }} \
        --query taskDefinition \
        --output json)" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ inputs.task_definition }}
        container-name: ${{ inputs.container-name }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ inputs.ecs-service }}
        cluster: ${{ inputs.ecs-cluster }}
        wait-for-service-stability: true
