name: 'Terraform'

on:
  workflow_call: 
    inputs:
      working-directory:
        description: 'Terraform working directory'
        type: string
        required: true
        default: './infra'

      environment:
        description: 'Deployment environment'
        type: string
        required: true
        default: 'deveplopment'

      aws-region: 
        description: 'AWS Region'
        type: string
        required: true
        default: 'us-east-1'

    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true

    outputs:
      ecr_repository:
        description: 'ECR Repository Name'
        value: ${{ jobs.terraform.outputs.ecr-repository }}
      ecs_cluster:
        description: 'ECS Cluster Name'
        value: ${{ jobs.terraform.outputs.ecs-cluster }}
      ecs_service:
        description: 'ECS Service Name'
        value: ${{ jobs.terraform.outputs.ecs-service }}
      task_definition:
        description: 'Task Definition Name'
        value: ${{ jobs.terraform.outputs.task-definition }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: |
        terraform apply -auto-approve -input=false
        echo "ecr-repository=$(terraform output -raw ecr_repository_name)" >> $GITHUB_OUTPUT
        echo "ecs-cluster=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_OUTPUT
        echo "ecs-service=$(terraform output -raw ecs_service_name)" >> $GITHUB_OUTPUT
        echo "task-definition=$(terraform output -raw task_definition_name)" >> $GITHUB_OUTPUT
    
    outputs:
      ecr-repository: ${{ steps.apply.outputs.ecr-repository }}
      ecs-cluster: ${{ steps.apply.outputs.ecs-cluster }}
      ecs-service: ${{ steps.apply.outputs.ecs-service }}
      task-definition: ${{ steps.apply.outputs.task-definition }}
